name: mapbox_gl_modified_platform_interface
description: A common platform interface for the mapbox_gl plugin.
version: 0.16.0
homepage: https://github.com/ithebest/mapbox_gl_modified

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
